/** @type {import('tailwindcss').Config} */
/** Shared public Design OS theme — consume via presets: [foundationPreset] */
export default {
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: '#15656f',
          dark: '#0b343c',
          light: '#458f98',
        },
        /* Meridian primitives */
        halo: {
          DEFAULT: '#f3f5f7',
          deep: '#dce1e8',
        },
        meridian: {
          deep: '#0b343c',
          DEFAULT: '#15656f',
          soft: '#458f98',
        },
        spark: {
          DEFAULT: '#e35a18',
          soft: '#ef7b42',
          deep: '#b84512',
        },
        /* Compatibility aliases — same hex as Meridian */
        cream: {
          DEFAULT: '#f3f5f7',
          deep: '#dce1e8',
        },
        emerald: {
          deep: '#0b343c',
          DEFAULT: '#15656f',
          soft: '#458f98',
        },
        gold: {
          DEFAULT: '#e35a18',
          soft: '#ef7b42',
        },
        ink: {
          DEFAULT: '#12161d',
          soft: '#596270',
        },
        obsidian: {
          DEFAULT: '#07090d',
          raised: '#11151c',
          line: '#1e2430',
        },
        void: {
          DEFAULT: '#07090d',
          raised: '#11151c',
          line: '#1e2430',
        },
        surface: {
          base: 'var(--color-surface-base)',
          raised: 'var(--color-surface-raised)',
          sunken: 'var(--color-surface-sunken)',
          overlay: 'var(--color-surface-overlay)',
          inverse: 'var(--color-surface-inverse)',
          'inverse-raised': 'var(--color-surface-inverse-raised)',
        },
        content: {
          primary: 'var(--color-content-primary)',
          secondary: 'var(--color-content-secondary)',
          muted: 'var(--color-content-muted)',
          disabled: 'var(--color-content-disabled)',
          inverse: 'var(--color-content-inverse)',
          link: 'var(--color-content-link)',
        },
        border: {
          subtle: 'var(--color-border-subtle)',
          DEFAULT: 'var(--color-border-default)',
          strong: 'var(--color-border-strong)',
          focus: 'var(--color-border-focus)',
          'on-inverse': 'var(--color-border-on-inverse)',
        },
        action: {
          primary: 'var(--color-action-primary)',
          'primary-hover': 'var(--color-action-primary-hover)',
          'primary-active': 'var(--color-action-primary-active)',
          soft: 'var(--color-action-primary-soft)',
          secondary: 'var(--color-action-secondary)',
          'secondary-hover': 'var(--color-action-secondary-hover)',
          danger: 'var(--color-action-danger)',
          'danger-hover': 'var(--color-action-danger-hover)',
          disabled: 'var(--color-action-disabled)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
        },
        status: {
          success: 'var(--color-status-success)',
          'success-surface': 'var(--color-status-success-surface)',
          warning: 'var(--color-status-warning)',
          'warning-surface': 'var(--color-status-warning-surface)',
          danger: 'var(--color-status-danger)',
          'danger-surface': 'var(--color-status-danger-surface)',
          info: 'var(--color-status-info)',
          'info-surface': 'var(--color-status-info-surface)',
        },
      },
      spacing: {
        'dos-xs': 'var(--space-xs)',
        'dos-sm': 'var(--space-sm)',
        'dos-md': 'var(--space-md)',
        'dos-lg': 'var(--space-lg)',
        'dos-xl': 'var(--space-xl)',
        'dos-2xl': 'var(--space-2xl)',
        'dos-3xl': 'var(--space-3xl)',
        'dos-4xl': 'var(--space-4xl)',
      },
      borderRadius: {
        'dos-none': 'var(--radius-none)',
        'dos-xs': 'var(--radius-xs)',
        'dos-sm': 'var(--radius-sm)',
        'dos-md': 'var(--radius-md)',
        'dos-lg': 'var(--radius-lg)',
        'dos-xl': 'var(--radius-xl)',
        'dos-2xl': 'var(--radius-2xl)',
        'dos-full': 'var(--radius-full)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-xl)',
      },
      boxShadow: {
        none: 'var(--shadow-none)',
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        'dos-xs': 'var(--shadow-xs)',
        'dos-sm': 'var(--shadow-sm)',
        'dos-md': 'var(--shadow-md)',
        'dos-lg': 'var(--shadow-lg)',
        'dos-xl': 'var(--shadow-xl)',
      },
      transitionDuration: {
        instant: 'var(--motion-instant)',
        fast: 'var(--motion-fast)',
        normal: 'var(--motion-normal)',
        slow: 'var(--motion-slow)',
      },
      transitionTimingFunction: {
        'dos-out': 'var(--ease-out)',
        'dos-in': 'var(--ease-in)',
        'dos-in-out': 'var(--ease-in-out)',
        dos: 'var(--ease-default)',
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        modal: 'var(--z-modal)',
        notification: 'var(--z-notification)',
      },
      ringColor: {
        dos: 'var(--color-focus-ring)',
        focus: 'var(--color-focus-ring)',
        'dos-inverse': 'var(--color-focus-ring-inverse)',
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        display: ['Sora', '"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        serif: ['Sora', '"IBM Plex Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-hero': [
          'clamp(2.25rem, 4.5vw, 3.5rem)',
          { lineHeight: '1.15', letterSpacing: '-0.03em', fontWeight: '600' },
        ],
        'display-section': [
          'clamp(1.75rem, 3vw, 2.25rem)',
          { lineHeight: '1.2', letterSpacing: '-0.025em', fontWeight: '600' },
        ],
        'display-card': ['1.25rem', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '600' }],
        lead: ['1.125rem', { lineHeight: '1.55' }],
        'lead-lg': ['1.25rem', { lineHeight: '1.55' }],
        body: ['1rem', { lineHeight: '1.6' }],
        meta: ['0.875rem', { lineHeight: '1.55' }],
        eyebrow: ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.14em' }],
      },
      maxWidth: {
        measure: '65ch',
        'measure-lead': '42ch',
        content: '75rem',
      },
    },
  },
}
